version: "3.8"
services:
  nodejs-sample:
    init: true
    build: .
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./data
        target: /tmp/nodejs/data
